### PR TITLE
Use one socket.io connection (fix duplicates)

### LINKED ISSUE #80: Duplicated websockets on re-renders

### PR DESCRIPTION
**Pull request by filipton**
Closes #80 

Remove all gateway websocket server, instead use global one.

### CODE REVIEW

File: frontend/src/socket.ts [hunk 1]
```diff
@@ -0,0 +1,13 @@
...
+import { WEBSOCKET_PATH, WEBSOCKET_URL } from "./logic/request";
+
+export const socket = io(WEBSOCKET_URL, {
+    transports: ["websocket"],
+    path: WEBSOCKET_PATH,
+    closeOnBeforeunload: true,
+    autoConnect: false,
+    auth: {
+        //token: getToken(),
+    },
```
Comment (maxidragon) [inline frontend/src/socket.ts:12]:
```suggestion
```

**Review by maxidragon — APPROVED** [review]
